fake_ticket_titles = [
    "Unable to Access Email Account After Password Reset",
    "Website Down: Error 500 on Homepage",
    "Request for New Laptop: Approval Needed",
    "Data Backup Failed on Server XYZ",
    "System Performance Slows During Peak Hours",
    "Software Installation Request: Adobe Photoshop",
    "User Account Locked Due to Multiple Login Attempts",
    "Printer Not Responding in Office 2B",
    "Error While Submitting Monthly Report in ERP System",
    "Request to Update Firewall Rules for New IP Range",
    "VPN Connection Drops Intermittently",
    "Lost Access to Shared Network Drive",
    "Request to Create a New User Account in CRM",
    "Mobile App Crashing on Launch for Multiple Users",
    "Server Room Temperature Exceeding Safe Levels",
    "Delay in Receiving Automated Alert Emails",
    "Keyboard Keys Not Functioning Properly",
    "High Latency Detected on Internal Network",
    "Database Maintenance Request for Optimization",
    "Login Issues After Password Policy Update",
    "Power Failure in Data Center: Emergency Support Needed",
    "Request for Additional Storage Space on Server",
    "Software License Expiry Notification",
    "Request to Schedule Training for New Software",
    "Error When Syncing Files Between Devices",
    "Update Required for Office Security Badges",
    "Broken Monitor in Conference Room 1A",
    "Website SSL Certificate Expired",
    "Issues with Two-Factor Authentication Setup",
    "Customer Unable to Complete Online Payment"
]

fake_users = [
    "John Doe",
    "Jane Smith",
    "Robert Johnson",
    "Emily Davis",
    "Michael Brown",
    "Sarah Wilson",
    "David Miller",
    "Jessica Taylor",
    "James Anderson",
    "Laura Thomas",
    "Daniel Moore",
    "Emma Jackson",
    "Matthew White",
    "Olivia Harris",
    "Christopher Martin",
    "Sophia Thompson",
    "Andrew Garcia",
    "Mia Martinez",
    "William Robinson",
    "Isabella Clark"
]
